import Footer from "@/components/Footer/Footer";
import Header from "@/components/Header/Header";
import MobileNav from "@/components/MobileNav/MobileNav";
import { Providers } from "@/redux/providers";
import styles from "./layout.module.css";
import "./globals.css";

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="ru">
      <body className={styles.wrapper}>
        <Providers>
          <Header className={styles.header} />
          <main className={styles.body}>{children}</main>
          <Footer className={styles.footer} />
        </Providers>
      </body>
    </html>
  );
}
